In [2]:
import numpy as np
import cv2

In [39]:
img = cv2.imread('./images/240_F_594773641_8rrPYslOpBs62dSOWKFi1awSfyj5szni.jpg')

In [50]:
print(img)


[[[108 106 236]
  [108 106 236]
  [108 106 236]
  ...
  [101 117 254]
  [101 117 254]
  [101 116 255]]

 [[109 105 234]
  [109 105 234]
  [109 105 234]
  ...
  [101 117 254]
  [100 116 253]
  [100 115 255]]

 [[110 105 228]
  [110 105 228]
  [110 105 228]
  ...
  [ 98 116 253]
  [ 97 115 252]
  [ 97 114 254]]

 ...

 [[114 101 139]
  [114 101 139]
  [116 101 139]
  ...
  [ 97  68 177]
  [ 96  67 176]
  [ 98  68 175]]

 [[107  97 133]
  [108  98 134]
  [111  99 135]
  ...
  [100  74 164]
  [ 99  73 163]
  [ 99  73 163]]

 [[113 104 137]
  [114 105 138]
  [117 105 141]
  ...
  [ 99  73 156]
  [ 98  72 155]
  [ 98  72 155]]]


In [6]:
img.shape

(240, 429, 3)

In [ ]:
cv2.imshow('flamingo', img)
cv2.waitKey(0)
cv2.destroyAllWindows